lesson:
  limit_words: 10
words:
  filter_type:
    all_word: "all_word"
    learned: "learned"
    not_learned: "not_learned"
paginate:
  users: 10
  words: 10
  lesson: 10
  categories: 10
  activities: 5
image_user:
  size: 50
  height: 50
  width: 50
answers:
  limit_answers: 4
  correct_answers: 1
